POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization:  bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzWiIsImlkIjoiNWZhY2YyNmYzODQ5YTI1M2JjMGQ3YWM5IiwiaWF0IjoxNjA1MTY5OTQ3fQ.gownypaBDYyeXnF6-fdr_grz4TXjw4z01M4q0uUBkM4

{
  "content": "I like to post a lot of notes",
  "important": true
}